//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamVersionChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamVersionChecker.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No branches found.
        /// </summary>
        public static string ErrorBranchesNotFound {
            get {
                return ResourceManager.GetString("ErrorBranchesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No depots found.
        /// </summary>
        public static string ErrorDepotsNotFound {
            get {
                return ResourceManager.GetString("ErrorDepotsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamApps not initialized.
        /// </summary>
        public static string ErrorSteamAppsNotFound {
            get {
                return ResourceManager.GetString("ErrorSteamAppsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found game!.
        /// </summary>
        public static string GameFound {
            get {
                return ResourceManager.GetString("GameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game found.
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for game....
        /// </summary>
        public static string GameSearching {
            get {
                return ResourceManager.GetString("GameSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing field tag.
        /// </summary>
        public static string MenuAddMissingFieldTag {
            get {
                return ResourceManager.GetString("MenuAddMissingFieldTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get oldest game.
        /// </summary>
        public static string MenuGetOldestGame {
            get {
                return ResourceManager.GetString("MenuGetOldestGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get playtime.
        /// </summary>
        public static string MenuGetPlaytime {
            get {
                return ResourceManager.GetString("MenuGetPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get random game.
        /// </summary>
        public static string MenuGetRandomGame {
            get {
                return ResourceManager.GetString("MenuGetRandomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set versions.
        /// </summary>
        public static string MenuSetVersions {
            get {
                return ResourceManager.GetString("MenuSetVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort links.
        /// </summary>
        public static string MenuSortLinks {
            get {
                return ResourceManager.GetString("MenuSortLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamVersionChecker.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing field.
        /// </summary>
        public static string TagMissingField {
            get {
                return ResourceManager.GetString("TagMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string TagUpdateAvailable {
            get {
                return ResourceManager.GetString("TagUpdateAvailable", resourceCulture);
            }
        }
    }
}
